name: Sekret test

on:
  push:
    paths:
      - '.github/workflows/secret.yml'

jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Testuję sekret
        run: |
          echo "Wysyłam zapytanie CURL"
          curl https://httpbin.org/get?token=${{ secrets.MY_SECRET }}
