name: testy

on: [push]

jobs:
  testowanie:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Ustawienie Pythona
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Instalacja pytest
        run: pip install pytest
      - name: Uruchom testy
        run: pytest
